/* Resource file indices for UFORMAT. */

#define F_MENU           0   /* Menu-tree */
#define M_ABOUT          7   /* STRING in tree F_MENU */
#define M_QUIT           16  /* STRING in tree F_MENU */

#define F_DIALOG         1   /* Form/Dialog-box */
#define F_MESSAGE        1   /* TEXT in tree F_DIALOG */
#define F_720            2   /* BUTTON in tree F_DIALOG */
#define F_144            3   /* BUTTON in tree F_DIALOG */
#define F_FORMAT         4   /* BUTTON in tree F_DIALOG */
#define F_QUIT           5   /* BUTTON in tree F_DIALOG */
#define F_TITLE          6   /* TEXT in tree F_DIALOG */
#define F_LABEL          7   /* FTEXT in tree F_DIALOG */
#define PROGRESS_BOX     8   /* BOX in tree F_DIALOG */
#define PROGRESS_POS     9   /* BOX in tree F_DIALOG */

#define F_ABOUT          2   /* Form/Dialog-box */
#define A_OK             4   /* BUTTON in tree F_ABOUT */

#define NO_DRIVER        0   /* Alert-string */

#define F_COMPLETE       1   /* Alert-string */

#define NO_WINDOW        2   /* Free String */

#define NO_DISKETTE      3   /* Free String */

#define SEARCHING        4   /* Free String */

#define WRITE_PROTECTED  5   /* Free String */

#define ABOUT            6   /* Free String */

#define FORMATTING       7   /* Free String */

#define INITIALIZING     8   /* Free String */

#define SUCCESS          9   /* Free String */

#define NOT_READY        10  /* Free String */

#define DISKETTE_ERROR   11  /* Free String */

#define HARDWARE_ERROR   12  /* Free String */

#define DRIVE_ABORTED    13  /* Free String */

#define INTERFACE        14  /* Free String */

#define TIMEOUT          15  /* Free String */

#define ERROR_CODE       16  /* Free String */
